import { run } from "./run.js";
import { compile } from "./compile.js";

// log this for fun
export const MEM = {
    MEM_SIZE: 1024 * 1024,
    SYS_REG_OFFSET:  0,
    SYS_REG_SIZE:  64,
    USER_REG_OFFSET:  64,
    USER_REG_SIZE:  64,
    STATIC_REG_OFFSET:  128,
    STATIC_REG_SIZE:  64 * 1024,
    HEAP_OFFSET:  128 + (64 * 1024),
    HEAP_SIZE:  (1024 * 1024) - (128 + (64 * 1024)),
    MAX_TOKENS: 4,
    MAX_INSTS: 1024
};

export const MODE = {
    NONE: 0,
    IMM: 1,
    DIR: 2
};

export const TYPE = {
    NONE: 0,
    BYTE: 1,
    INT: 2,
    FLOAT: 3
};

export const TYPE_SIZES = {
    [TYPE.NONE]: 0,
    [TYPE.BYTE]: 1,
    [TYPE.INT]: 4,
    [TYPE.FLOAT]: 4
};

export const TYPE_SUFFIXES = {
    [TYPE.NONE]: '',
    [TYPE.BYTE]: '_B',
    [TYPE.INT]: '_I',
    [TYPE.FLOAT]: '_F'
};

export const OP = {
    NONE: 0,
    LOAD_B: 1,
    LOAD_I: 2,
    LOAD_F: 3,
    STORE_B: 4,
    STORE_I: 5,
    STORE_F: 6,
    DEREF_B: 7,
    DEREF_I: 8,
    DEREF_F: 9,
    ADD_B: 10,
    ADD_I: 11,
    ADD_F: 12,
    SUB_B: 13,
    SUB_I: 14,
    SUB_F: 15,
    MUL_B: 16,
    MUL_I: 17,
    MUL_F: 18,
    DIV_B: 19,
    DIV_I: 20,
    DIV_F: 21,
    MOD_B: 22,
    MOD_I: 23,
    MOD_F: 24,
    AND_B: 25,
    AND_I: 26,
    OR_B: 27,
    OR_I: 28,
    XOR_B: 29,
    XOR_I: 30,
    NOT_B: 31,
    NOT_I: 32,
    SHL_B: 33,
    SHL_I: 34,
    SHR_B: 35,
    SHR_I: 36,
    OUT_B: 37,
    OUT_I: 38,
    OUT_F: 39,
    OUT_C: 40,
    OUT_S: 41,
    CMP_B: 42,
    CMP_I: 43,
    CMP_F: 44,
    IFE: 45,
    IFNE: 46,
    IFL: 47,
    IFLE: 48,
    IFG: 49,
    IFGE: 50,
    JMP: 51,
    ALLOC: 52,
    FREE: 53,
    CAST_BI: 54,
    CAST_BF: 55,
    CAST_IB: 56,
    CAST_IF: 57,
    CAST_FB: 58,
    CAST_FI: 59,
    HALT: 60,
    FLUSH: 61
};

export const OP_MODES = {
    [OP.NONE]: MODE.NONE,
    [OP.LOAD_B]: MODE.IMM,
    [OP.LOAD_I]: MODE.IMM,
    [OP.LOAD_F]: MODE.IMM,
    [OP.STORE_B]: MODE.DIR,
    [OP.STORE_I]: MODE.DIR,
    [OP.STORE_F]: MODE.DIR,
    [OP.DEREF_B]: MODE.DIR,
    [OP.DEREF_I]: MODE.DIR,
    [OP.DEREF_F]: MODE.DIR,
    [OP.ADD_B]: MODE.IMM,
    [OP.ADD_I]: MODE.IMM,
    [OP.ADD_F]: MODE.IMM,
    [OP.SUB_B]: MODE.IMM,
    [OP.SUB_I]: MODE.IMM,
    [OP.SUB_F]: MODE.IMM,
    [OP.MUL_B]: MODE.IMM,
    [OP.MUL_I]: MODE.IMM,
    [OP.MUL_F]: MODE.IMM,
    [OP.DIV_B]: MODE.IMM,
    [OP.DIV_I]: MODE.IMM,
    [OP.DIV_F]: MODE.IMM,
    [OP.MOD_B]: MODE.IMM,
    [OP.MOD_I]: MODE.IMM,
    [OP.MOD_F]: MODE.IMM,
    [OP.AND_B]: MODE.IMM,
    [OP.AND_I]: MODE.IMM,
    [OP.OR_B]: MODE.IMM,
    [OP.OR_I]: MODE.IMM,
    [OP.XOR_B]: MODE.IMM,
    [OP.XOR_I]: MODE.IMM,
    [OP.NOT_B]: MODE.IMM,
    [OP.NOT_I]: MODE.IMM,
    [OP.SHL_B]: MODE.IMM,
    [OP.SHL_I]: MODE.IMM,
    [OP.SHR_B]: MODE.IMM,
    [OP.SHR_I]: MODE.IMM,
    [OP.OUT_B]: MODE.IMM,
    [OP.OUT_I]: MODE.IMM,
    [OP.OUT_F]: MODE.IMM,
    [OP.OUT_C]: MODE.IMM,
    [OP.OUT_S]: MODE.IMM,
    [OP.CMP_B]: MODE.IMM,
    [OP.CMP_I]: MODE.IMM,
    [OP.CMP_F]: MODE.IMM,
    [OP.IFE]: MODE.NONE,
    [OP.IFNE]: MODE.NONE,
    [OP.IFL]: MODE.NONE,
    [OP.IFLE]: MODE.NONE,
    [OP.IFG]: MODE.NONE,
    [OP.IFGE]: MODE.NONE,
    [OP.JMP]: MODE.IMM,
    [OP.ALLOC]: MODE.IMM,
    [OP.FREE]: MODE.IMM,
    [OP.CAST_BI]: MODE.IMM,
    [OP.CAST_BF]: MODE.IMM,
    [OP.CAST_IB]: MODE.IMM,
    [OP.CAST_IF]: MODE.IMM,
    [OP.CAST_FB]: MODE.IMM,
    [OP.CAST_FI]: MODE.IMM,
    [OP.HALT]: MODE.NONE,
    [OP.FLUSH]: MODE.NONE
};

export const OP_TYPES = {
    [OP.NONE]: TYPE.NONE,
    [OP.LOAD_B]: TYPE.BYTE,
    [OP.LOAD_I]: TYPE.INT,
    [OP.LOAD_F]: TYPE.FLOAT,
    [OP.STORE_B]: TYPE.BYTE,
    [OP.STORE_I]: TYPE.INT,
    [OP.STORE_F]: TYPE.FLOAT,
    [OP.DEREF_B]: TYPE.BYTE,
    [OP.DEREF_I]: TYPE.INT,
    [OP.DEREF_F]: TYPE.FLOAT,
    [OP.ADD_B]: TYPE.BYTE,
    [OP.ADD_I]: TYPE.INT,
    [OP.ADD_F]: TYPE.FLOAT,
    [OP.SUB_B]: TYPE.BYTE,
    [OP.SUB_I]: TYPE.INT,
    [OP.SUB_F]: TYPE.FLOAT,
    [OP.MUL_B]: TYPE.BYTE,
    [OP.MUL_I]: TYPE.INT,
    [OP.MUL_F]: TYPE.FLOAT,
    [OP.DIV_B]: TYPE.BYTE,
    [OP.DIV_I]: TYPE.INT,
    [OP.DIV_F]: TYPE.FLOAT,
    [OP.MOD_B]: TYPE.BYTE,
    [OP.MOD_I]: TYPE.INT,
    [OP.MOD_F]: TYPE.FLOAT,
    [OP.AND_B]: TYPE.BYTE,
    [OP.AND_I]: TYPE.INT,
    [OP.OR_B]: TYPE.BYTE,
    [OP.OR_I]: TYPE.INT,
    [OP.XOR_B]: TYPE.BYTE,
    [OP.XOR_I]: TYPE.INT,
    [OP.NOT_B]: TYPE.BYTE,
    [OP.NOT_I]: TYPE.INT,
    [OP.SHL_B]: TYPE.BYTE,
    [OP.SHL_I]: TYPE.INT,
    [OP.SHR_B]: TYPE.BYTE,
    [OP.SHR_I]: TYPE.INT,
    [OP.OUT_B]: TYPE.BYTE,
    [OP.OUT_I]: TYPE.INT,
    [OP.OUT_F]: TYPE.FLOAT,
    [OP.OUT_C]: TYPE.BYTE,
    [OP.OUT_S]: TYPE.INT,
    [OP.CMP_B]: TYPE.BYTE,
    [OP.CMP_I]: TYPE.INT,
    [OP.CMP_F]: TYPE.FLOAT,
    [OP.IFE]: TYPE.NONE,
    [OP.IFNE]: TYPE.NONE,
    [OP.IFL]: TYPE.NONE,
    [OP.IFLE]: TYPE.NONE,
    [OP.IFG]: TYPE.NONE,
    [OP.IFGE]: TYPE.NONE,
    [OP.JMP]: TYPE.INT,
    [OP.ALLOC]: TYPE.INT,
    [OP.FREE]: TYPE.INT,
    [OP.CAST_BI]: TYPE.BYTE,
    [OP.CAST_BF]: TYPE.BYTE,
    [OP.CAST_IB]: TYPE.INT,
    [OP.CAST_IF]: TYPE.INT,
    [OP.CAST_FB]: TYPE.FLOAT,
    [OP.CAST_FI]: TYPE.FLOAT,
    [OP.HALT]: TYPE.NONE,
    [OP.FLUSH]: TYPE.NONE
};

export const PRE_OP = {
    NONE: 0,
    B: 1,
    I: 2,
    F: 3,
    S: 4,
    BA: 5,
    IA: 6,
    FA: 7,
    LBL: 8
};

export const PRE_OP_TYPES = {
    [PRE_OP.NONE]: TYPE.NONE,
    [PRE_OP.B]: TYPE.BYTE,
    [PRE_OP.I]: TYPE.INT,
    [PRE_OP.F]: TYPE.FLOAT,
    [PRE_OP.S]: TYPE.NONE,
    [PRE_OP.BA]: TYPE.BYTE,
    [PRE_OP.IA]: TYPE.INT,
    [PRE_OP.FA]: TYPE.FLOAT,
    [PRE_OP.LBL]: TYPE.NONE
}

export const asm = {
    run,
    compile
};
